apiVersion: apps/v1
kind: Deployment
metadata:
  name: skin-disease-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skin-disease
  template:
    metadata:
      labels:
        app: skin-disease
    spec:
      containers:
      - name: skin-disease
        image: mimouneayoub/skin-disease:latest
        ports:
        - containerPort: 9000
