apiVersion: v1
kind: Service
metadata:
  name: skin-disease-service
spec:
  type: NodePort
  selector:
    app: skin-disease
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30001
